### ISSUE TITLE
Errors on the plugin

### ISSUE THREAD

**Issue by XHiddenProjects** [LanternServer/LanternMC-experimental-plugin#1]
Here is a list of errors that I have caught:
* plugin.yml: line 8: missing ":"
* Main.php: [
	- line 3: missing ";"
	- line: 5-7: missing: ";"
	- line: 6: pocketmine\command\"CommandSender";
]

**Comment by LanternServer** [comment]
thx!

**Comment by XHiddenProjects** [comment]
no problem

**Comment by XHiddenProjects** [comment]
for some reason its suppost to be "pocketmine\command\CommandSender"

**Comment by XHiddenProjects** [comment]
* plugin.yml: [
	- permission: alanternmc.cmd.lanternMC is not registered properly
	- permission: rename it as "permissions"
	- permission: must be a seperate from commands
	- usage: Must be "/lanternMC" otherwise use all aliases: [/lanternmc]
	- Make sure the API matches with current pocketmine version
]
* Main.php: [
	- line 6: missing ";"
	- line 9: use "class AdvancedModeration extends PluginBase implements Listener"
	- include: [
		* use pocketmine\Server;
		* use pocketmine\Player;
		* use pocketmine\event\Listener;
		]
	- must have 2 cases for 2 commands(case "lanternMC":) {new_line} (case "lanternmc":)
	- missing "break;" on line: 23 and 24
	

]
